// Layout racine: hydrate la session côté serveur et fournit le fallback SWR
// Fonction pour précharger la session et rendre l'en-tête authentifié
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { cookies } from 'next/headers'
import { getSessionFromCookieStore } from '@/lib/server/auth'
import { db } from '@/db'
import { users } from '@/db/schema'
import { eq } from 'drizzle-orm'
import AuthButtons from './components/AuthButtons'
import ClientSWRProvider from './components/ClientSWRProvider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Server-side: read cookies and fetch the user if present so header can
  // render immediately without a client fetch.
  const cookieStore = await cookies()
  const userId = await getSessionFromCookieStore(cookieStore)

  let initialSession = null
  if (userId) {
    const userData = await db
      .select({ id: users.id, name: users.name, email: users.email })
      .from(users)
      .where(eq(users.id, userId))
      .limit(1)

    if (userData.length > 0) {
      const u = userData[0]
      initialSession = { id: String(u.id), name: u.name, email: u.email }
    } else {
      // If the cookie pointed to a missing user, clear it to avoid stale state
      cookieStore.delete('user_id')
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSWRProvider fallback={initialSession ? { '/api/auth/check': initialSession } : {}}>
          {/* Top-right header area for auth controls */}
          <div className="absolute top-6 right-6 z-50">
            {/* Pass the server-fetched session as initialSession */}
            {/* AuthButtons is a client component that accepts this prop */}
            <AuthButtons initialSession={initialSession} />
          </div>

          {children}
        </ClientSWRProvider>
      </body>
    </html>
  );
}
